import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/packages/auth/session";
import { hasPermission } from "@/packages/auth/roles";
import { leadRepository } from "@/packages/database/repositories/leadRepository";
import { customerRepository } from "@/packages/database/repositories/customerRepository";
import { bantEngine } from "@/packages/sales/bantEngine";
import { proposalEngine } from "@/packages/sales/proposalEngine";
import { dealStageEngine } from "@/packages/sales/dealStageEngine";
import { handleApiError } from "@/packages/errors/errorHandler";
import { ForbiddenError, NotFoundError } from "@/packages/errors/AppError";

export const dynamic = "force-dynamic";

export async function POST(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const user = await requireAuth(req);

    const canEdit = user.roles.some((r) => hasPermission(r, "leads:edit"));
    if (!canEdit) {
      throw new ForbiddenError("You do not have permission to generate engineering proposals.");
    }

    const leadId = params.id;
    const lead = await leadRepository.findById(leadId);
    if (!lead) {
      throw new NotFoundError(`Lead with ID ${leadId} not found`);
    }

    const customer = await customerRepository.findById(lead.customer_id);

    // Compute BANT breakdown
    const bant = bantEngine.computeBantScore({
      name: customer?.name,
      email: customer?.email,
      phone: customer?.phone || undefined,
      company: customer?.country || undefined,
      problem: lead.problem_statement || undefined,
      rawBudget: lead.budget_range || undefined,
      rawTimeline: lead.timeline || undefined,
      roleTitle: lead.decision_maker_status || undefined,
    });

    const readiness = proposalEngine.isProposalReady(lead, bant, customer);
    const scope = proposalEngine.generateScope(lead, bant, customer);

    // Advance to PROPOSAL stage if currently in earlier stage
    if (readiness.ready && (lead.stage === "NEW" || lead.stage === "CONTACTED" || lead.stage === "QUALIFIED")) {
      await dealStageEngine.transitionStage({
        leadId,
        targetStage: "PROPOSAL",
        actorType: "USER",
        actorId: user.id,
        reason: "Preliminary engineering proposal scope generated by sales engineer",
      });
    }

    return NextResponse.json({
      success: true,
      leadId,
      readiness,
      proposalScope: scope,
    });
  } catch (err) {
    return handleApiError(err, "AdminLeadProposalAPI");
  }
}
